---
exemptProjects: true
exemptMilestones: true
exemptLabels:
  - Pinned
  - Security

daysUntilStale: 60
daysUntilClose: false

staleLabel: Stale

markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will not be closed. If you wish to carry on just leave a
  comment. Thank you for your contributions.
pulls:
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will not be closed. If you wish to carry on just leave a
    comment. Thank you for your contributions.
