---
name: Test documentation

env:
  CI_FORCE_COLORS_POETRY: --ansi
  CI_FORCE_COLORS_SPHINX: --color

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - "!*"
    branches:
      - master

  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Tests on ${{ matrix.os }} with default python
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'pull_request' ||
      (github.event_name == 'push' &&
      contains(toJson(github.event.head_commit.message), '[skip ci]') == false)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3

      - name: Fetch origin/main
        #: https://github.com/Bachmann1234/diff_cover#troubleshooting
        run: git fetch --no-tags origin master:refs/remotes/origin/master

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run tests with tox
        run: tox -n docs
