---
name: QA

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

  push:
    tags:
      - "!*"
    branches:
      - master

  pull_request:

jobs:
  build:
    name: Run QA Tools
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox poetry
      - name: Run pre-commit with tox
        run: tox -e pre-commit
